CREATE TABLE person(
    id BIGINT PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    gender VARCHAR(255) NOT NULL,
    created_at DATE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;